name: Deploy Demo Fronted

on:
  push:
    branches:
    - demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Demo
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.16.0

    - name: Install Yarn
      run: npm install --force yarn

    - name: Install dependencies
      run: yarn

    - name: Update prisma schema
      run: |
        cd apps/cake/prisma
        npx prisma generate
        cd ../../

    - name: Install nx
      run: npm install -g @nrwl/cli | npm install

    - name: Build Frontend
      run: yarn nx run frontend:build:demo

    - name: Deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './dist/apps/frontend/demo/'      # optional: defaults to entire repository
